- name: Install Google Chrome
  hosts: all
  become: yes
  tasks:
    - name: Add Google Chrome APT key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present

    - name: Create default Chrome preferences directory
      file:
        path: /etc/opt/chrome/policies/managed
        state: directory
        mode: '0755'

    # Does not work yet...
    # - name: Disable first-run prompts in Chrome
    #   copy:
    #     dest: /etc/opt/chrome/policies/managed/first_run.json
    #     content: |
    #       {
    #         "BrowserSettings": {
    #           "ImportBookmarks": false,
    #           "ShowFirstRunBubble": false,
    #           "SuppressFirstRunDefaultBrowserPrompt": true
    #         }
    #       }
    #     mode: '0644'